version: "3.9"
services:
  orders-db:
    image: postgres:latest
    container_name: orders-db-test
    ports:
      - 8283:8080
      - 54323:5432
    volumes:
      - "orders-db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
volumes:
  orders-db: