server:
  port: 8183
spring:
  datasource:
    initialization-mode: always
    schema: classpath:/schema.sql
    url: jdbc:postgresql://${ORDERS_DB_HOST:localhost}:${ORDERS_DB_PORT:54323}/orders
    username: "orders"
    password: "orders"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
  application:
    name: orders-service

eureka:
  instance:
    hostname: ${ORDERS_HOST:localhost}
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8182/eureka/}
  healthcheck:
    enabled: true

management:
  endpoint:
    shutdown:
      enabled: true
    heapdump:
      enabled: true
    logfile:
      enabled: true
    info:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: @project.version@

feign:
  circuitbreaker:
    enabled: true

logging:
  level:
    root: debug