server:
  port: 8183
spring:
  application:
    name: orders-service

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8182/eureka/}
  healthcheck:
    enabled: true

management:
  endpoint:
    shutdown:
      enabled: true
    heapdump:
      enabled: true
    logfile:
      enabled: true
    info:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: @project.version@