server:
  port: 8183
spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:file:~/.microfood/orders/data
    driver-class-name: org.h2.Driver
    username: "sa"
    password: ""
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create
  application:
    name: orders-service
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  instance:
    hostname: ${ORDERS_HOST:localhost}
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8182/eureka/}
  healthcheck:
    enabled: true

management:
  endpoint:
    shutdown:
      enabled: true
    heapdump:
      enabled: true
    logfile:
      enabled: true
    info:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: @project.version@

logging:
  level:
    root: debug